modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/ZadenOwer/create-utils-and-resources/issues/"

[[mods]]
modId="create-utils-and-resources"
version="1.20.1-1.0.0"
displayName="Create: Utils and Resources"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-utils-and-resources"
logoFile="createuar_icon.png"
authors="ZadenOwer"
description='''
§7 Some utils blocks and resources for the Create§i mod!
'''

[[dependencies.create-utils-and-resources]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create-utils-and-resources]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create-utils-and-resources]]
    modId="create"
    mandatory=true
    versionRange="[6.0.2,6.1.0)"
    ordering="NONE"
    side="BOTH"
